INSERT INTO table_for_test(name, last_name) VALUES ('Johnny', 'Depp');
INSERT INTO table_for_test(name, last_name) VALUES ('Al', 'Pacino');
INSERT INTO table_for_test(name, last_name) VALUES ('Robert', 'De Niro');
INSERT INTO table_for_test(name, last_name) VALUES ('Kevin', 'Spacey');
INSERT INTO table_for_test(name, last_name) VALUES ('Bruce', 'Willis');
INSERT INTO table_for_test(name, last_name) VALUES ('Russell', 'Crowe');
INSERT INTO table_for_test(name, last_name) VALUES ('Brad', 'Pitt');
INSERT INTO table_for_test(name, last_name) VALUES ('Leonardo', 'DiCaprio');
INSERT INTO table_for_test(name, last_name) VALUES ('Tom', 'Cruise');
INSERT INTO table_for_test(name, last_name) VALUES ('Edward', 'Norton');